config/routes.rb
Rails.application.routes.draw do
	resource :session
	resources :customers , only: %i(show) do 
		get 'matches', on: :member
		get 'adopt', on: :member
	end
	resources :pets, only: %i(index show)
	scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
		resources :pets, only: %i(show create) do 
			get 'matches', on: :member
		end
		resources :customers, only: %i(show create) do 
			get 'matches', on: :member
			post 'adopt', on: :member
		end
	end

	mount ActionCable.server => "/cable"

	root :to => 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < Pet
	validates_absence_of :breed
end

app/models/customer.rb
class Customer < ApplicationRecord
	store :preference, :accessors => [:age, :species, :breed]
	validates_presence_of :name
end

app/models/dog.rb
class Dog < Pet
	validates_presence_of :breed
	BREEDS = %w(labrador poodle spaniel terrier)


end

app/models/pet.rb
class Pet < ApplicationRecord
	validates_presence_of :name, :age
	geocoded_by :address   
	after_validation :geocode  

	after_create_commit do 
		NotificationsBroadcastJob.perform_later(self)
	end        
end

app/models/rabbit.rb
class Rabbit < Pet
	validates_absence_of :breed
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

end

app/controllers/api_v1/customers_controller.rb
class ApiV1::CustomersController < ApiController
	before_action :find_customer, except: %i(create)

	def show
		render :json => @customer.to_json
	end

	def create
		@customer = Customer.new(
			name: params[:name],
			age: params[:age].to_i,
			species: params[:species].capitalize,
			breed: params[:breed]
			)
		if @customer.save
			render :json => { :customer => @customer.to_json, :message => "Created successfully!"}
		else
			render :json => { :message => "Please insert the name!"}, :status => 400
		end
	end

	def matches
		if @customer.preference == {}
			@pets = Pet.all.where(is_adopted: false)
		else
			@pets = Pet.where(type: @customer.species).
								where(age: @customer.age).
								where(breed: @customer.breed).
								where(is_adopted: false)
		end
		render :json => { :message => "Here is your matching list", :list => JSON.parse(@pets.to_json) }
	end


	def adopt
		@pet = Pet.find(params[:pet_id])
		@pet.is_adopted = true
		@pet.save
		render :json => { :message => "thank you for your kindness!"}, status => 200
	end

	private

	def find_customer
		@customer = Customer.find(params[:id])
	end
end

app/controllers/api_v1/pets_controller.rb
class ApiV1::PetsController < ApiController 
	
	def show
		@pet = Pet.find(params[:id])
		render :json => @pet.to_json
	end

	def create
		@pet = Pet.new( 
			type: params[:type].capitalize, 
			name: params[:name], 
			age: params[:age], 
			breed: params[:breed],
			address: params[:address] )
		if @pet.save
			render :json => { :pet => @pet.to_json ,:message => "OK!!!!!!!!"}
		else
			render :json => { :message => "please type the correct data" }, :status => 400
		end
	
	end

	def matches
		@pet = Pet.find(params[:id])
		if @pet.is_adopted == true
			render :json => { :pet => @pet.name, :message => "This pet is no longer available to adopt!"}
		else
			@customers = Customer.where(preference: nil)
			@customers = @customers + Customer.where('preference LIKE ? OR preference LIKE ? OR preference LIKE ? ', "%species: #{@pet.type}\n%", "%age: #{@pet.age}\n%", "%breed: #{@pet.breed}\n%")
			render :json => { :message => "Here is the matching list", :list => JSON.parse(@customers.to_json) }						
		end
		
	end







end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Identification
  protect_from_forgery with: :exception
end

app/controllers/concerns/identification.rb
module Identification
  extend ActiveSupport::Concern
  
  included do
    before_action :mark_current_user
  end

  private
    def mark_current_user
      identify_user(cookies.signed[:user_id]) || redirect_to(new_session_path)
    end

    def identify_user(user_id)
      if authenticated_user = Customer.find_by(id: user_id)
        cookies.signed[:user_id] ||= user_id
        @current_user = authenticated_user
      end
    end

    def erase_user
      ActionCable.server.disconnect(current_user: @current_user)
      @current_user = nil
      cookies.delete(:user_id)
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :find_customer, except: :index


	def show 
	end

	def matches
		if @customer.preference == {}
			@pets = Pet.all.where(is_adopted: false)
		else
			@pets = Pet.where(type: @customer.species).
								where(age: @customer.age).
								where(breed: @customer.breed).
								where(is_adopted: false)
		end
	end

	def adopt
		@pet = Pet.find(params[:pet_id])
		@pet.is_adopted = true
		@pet.save
	end


	private 

		def find_customer
			@customer = Customer.find(params[:id])
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end
	
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

	def index 
		@pets = Pet.all
	end

	def show
		@pet = Pet.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :mark_current_user, only: %i( new create )

  def new
    @customers = Customer.all
  end

  def create
    identify_user(params[:user_id])
    redirect_to root_path
  end

  def destroy
    erase_user
    redirect_to new_session_url
  end
end

app/helpers/api_v1/customers_helper.rb
module ApiV1::CustomersHelper
end

app/helpers/api_v1/pets_helper.rb
module ApiV1::PetsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/customers/_pet.html.erb
<li> 
	Name: <%= pet.name %> 
	<ul>
		<li>Age: <%= pet.age %></li>
		<% if @customer %>
			<li><%= link_to 'adopt this pet!', adopt_customer_path(@customer, pet_id: pet.id) %></li>
		<% else %>
			<li><%= link_to 'adopt this pet!', adopt_customer_path(customer, pet_id: pet.id) %></li>
		<% end  %>
	</ul>
</li>

app/views/customers/adopt.html.erb
<h1>Congratulation! <%= @customer.name %></h1>

<h2>you've already aopted this cute pet!</h2>
<p>
	Name: <%= @pet.name %><br>
	Species: <%= @pet.type %><br>
	<%if @pet.type == 'Dog' %>
		Breed: <%= @pet.breed %><br>
	<% end %>
	Age: <%= @pet.age %><br>

</p>

app/views/customers/matches.html.erb
<h1>Hi <%= @customer.name %>!
	<small>
		Here is your match list:
	</small>
</h1>
<ul id="match-list">
	<% @pets.each do |pet| %>
		<%= render :partial => "pet", :locals => { :pet => pet } %>
	<% end %>
</ul>

app/views/customers/show.html.erb
<h1>Welcome <%= @customer.name %>!</h1>

<p>You are looking for a pet like:</p>
<ul>
	<li>Age: <%= @customer.age%></li>
	<li>Species: <%= @customer.species %></li>
	<% if @customer.species == "Dog" %>
		<li>Breed: <%= @customer.breed %></li>
	<% end %>
</ul>


<%= link_to 'See my matches!', matches_customer_path(@customer) %>

app/views/home/index.html.erb
<h1>Welcome to Pets world!</h1>
<h3>Here you can do...</h3>
<%= link_to 'Show the pet\'s condition that I looking for', customer_path(@current_user) %> <br>
<%= link_to 'See all the pets', pets_path %> <br>

app/views/pets/index.html.erb
<% google_map_config =Rails.application.config_for(:google_map) %>

<div id="map"></div>
<% @pets.each do |pet| %>
  <ul>
    <li>Name: <%= pet.name %></li>
    <ul>
      <li>age: <%= pet.age %></li>
      <li>species: <%= pet.type %></li>
      <% if !pet.breed.nil? %>
        <li>breed: <%= pet.breed %></li>
      <% end %>
    </ul>
  </ul>  
<% end %>


<script>
  function initMap() { 
    var myLatLng = {lat: 22.431081, lng: 114.105857};
    var map = new google.maps.Map(document.getElementById('map'), {
      center: myLatLng,
      scrollwheel: false,
      zoom: 12
    });

    setMarkers(map);
    setGeolocation(map);
  }
    

  function setGeolocation(map){
    var infoWindow = new google.maps.InfoWindow({map: map});

    // HTML5 geolocation.
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var pos = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };

        infoWindow.setPosition(pos);
        infoWindow.setContent('Here you are!');
        map.setCenter(pos);
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
      infoWindow.setPosition(pos);
      infoWindow.setContent(browserHasGeolocation ?
        'Error: The Geolocation service failed.' :
        'Error: Your browser doesn\'t support geolocation.');
      }
    }

  <% info_list = [] %>
  <% @pets.map do |pet| %>
    <% info_list.push([h(pet.name), pet.latitude, pet.longitude]) %>
  <% end %>

  var pets_info = <%= raw(info_list)  %>

  function setMarkers(map){

    for(var i = 0; i < pets_info.length; i++) {
      var info = pets_info[i];
      var marker = new google.maps.Marker({
        position: {lat: info[1], lng: info[2]},
        map: map,
        html: info[0],
        id: i,
      });

      google.maps.event.addListener(marker, 'click', function(){
        var infowindow = new google.maps.InfoWindow({
          id: this.id,
          content:this.html,
          position:this.getPosition()
        });
        infowindow.open(map);
      });
    }
  }  
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= google_map_config['api_key'] %>&callback=initMap"
    async defer></script>

app/views/pets/show.html.erb
<header><h1 class="display-4"><%= @pet.name %></h1></header>

<p>Address: <%= @pet.address %></p>
<p>Coordinates: <%= @pet.latitude %> <%= @pet.longitude %></p>

    <div id="map"></div>
    <script>
      function initMap() {
        var myLatLng = {lat: <%= @pet.latitude %>, lng: <%= @pet.longitude %>};

        // Create a map object and specify the DOM element for display.
        var map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          scrollwheel: false,
          zoom: 15
        });

        // Create a marker and set its position.
        var marker = new google.maps.Marker({
          map: map,
          position: myLatLng,
          title: '<%= @pet.name %>'
        });
      }



    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAenIzCgvNqINyZVd3MoGaCqCDN2bDqFYo&callback=initMap"
        async defer></script>